/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model.tables.daos;


import com.rsa.rsaApplication.model.tables.PriKey;
import com.rsa.rsaApplication.model.tables.records.PriKeyRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PriKeyDao extends DAOImpl<PriKeyRecord, com.rsa.rsaApplication.model.tables.pojos.PriKey, Integer> {

    /**
     * Create a new PriKeyDao without any configuration
     */
    public PriKeyDao() {
        super(PriKey.PRI_KEY, com.rsa.rsaApplication.model.tables.pojos.PriKey.class);
    }

    /**
     * Create a new PriKeyDao with an attached configuration
     */
    public PriKeyDao(Configuration configuration) {
        super(PriKey.PRI_KEY, com.rsa.rsaApplication.model.tables.pojos.PriKey.class, configuration);
    }

    @Override
    public Integer getId(com.rsa.rsaApplication.model.tables.pojos.PriKey object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.rsa.rsaApplication.model.tables.pojos.PriKey> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(PriKey.PRI_KEY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.rsa.rsaApplication.model.tables.pojos.PriKey> fetchById(Integer... values) {
        return fetch(PriKey.PRI_KEY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.rsa.rsaApplication.model.tables.pojos.PriKey fetchOneById(Integer value) {
        return fetchOne(PriKey.PRI_KEY.ID, value);
    }

    /**
     * Fetch records that have <code>pri_key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.rsa.rsaApplication.model.tables.pojos.PriKey> fetchRangeOfPriKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(PriKey.PRI_KEY.PRI_KEY_, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>pri_key IN (values)</code>
     */
    public List<com.rsa.rsaApplication.model.tables.pojos.PriKey> fetchByPriKey(String... values) {
        return fetch(PriKey.PRI_KEY.PRI_KEY_, values);
    }

    /**
     * Fetch records that have <code>usr_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.rsa.rsaApplication.model.tables.pojos.PriKey> fetchRangeOfUsrId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(PriKey.PRI_KEY.USR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>usr_id IN (values)</code>
     */
    public List<com.rsa.rsaApplication.model.tables.pojos.PriKey> fetchByUsrId(Integer... values) {
        return fetch(PriKey.PRI_KEY.USR_ID, values);
    }
}
