/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model.tables.records;


import com.rsa.rsaApplication.model.tables.PriKey;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PriKeyRecord extends UpdatableRecordImpl<PriKeyRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 213129394;

    /**
     * Setter for <code>public.pri_key.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pri_key.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pri_key.pri_key</code>.
     */
    public void setPriKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pri_key.pri_key</code>.
     */
    public String getPriKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pri_key.usr_id</code>.
     */
    public void setUsrId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pri_key.usr_id</code>.
     */
    public Integer getUsrId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PriKey.PRI_KEY.ID;
    }

    @Override
    public Field<String> field2() {
        return PriKey.PRI_KEY.PRI_KEY_;
    }

    @Override
    public Field<Integer> field3() {
        return PriKey.PRI_KEY.USR_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPriKey();
    }

    @Override
    public Integer component3() {
        return getUsrId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPriKey();
    }

    @Override
    public Integer value3() {
        return getUsrId();
    }

    @Override
    public PriKeyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PriKeyRecord value2(String value) {
        setPriKey(value);
        return this;
    }

    @Override
    public PriKeyRecord value3(Integer value) {
        setUsrId(value);
        return this;
    }

    @Override
    public PriKeyRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PriKeyRecord
     */
    public PriKeyRecord() {
        super(PriKey.PRI_KEY);
    }

    /**
     * Create a detached, initialised PriKeyRecord
     */
    public PriKeyRecord(Integer id, String priKey, Integer usrId) {
        super(PriKey.PRI_KEY);

        set(0, id);
        set(1, priKey);
        set(2, usrId);
    }
}
