/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model.tables.records;


import com.rsa.rsaApplication.model.tables.PubKey;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PubKeyRecord extends UpdatableRecordImpl<PubKeyRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 833502040;

    /**
     * Setter for <code>public.pub_key.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pub_key.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pub_key.pub_key</code>.
     */
    public void setPubKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pub_key.pub_key</code>.
     */
    public String getPubKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pub_key.usr_id</code>.
     */
    public void setUsrId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pub_key.usr_id</code>.
     */
    public Integer getUsrId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PubKey.PUB_KEY.ID;
    }

    @Override
    public Field<String> field2() {
        return PubKey.PUB_KEY.PUB_KEY_;
    }

    @Override
    public Field<Integer> field3() {
        return PubKey.PUB_KEY.USR_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPubKey();
    }

    @Override
    public Integer component3() {
        return getUsrId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPubKey();
    }

    @Override
    public Integer value3() {
        return getUsrId();
    }

    @Override
    public PubKeyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PubKeyRecord value2(String value) {
        setPubKey(value);
        return this;
    }

    @Override
    public PubKeyRecord value3(Integer value) {
        setUsrId(value);
        return this;
    }

    @Override
    public PubKeyRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PubKeyRecord
     */
    public PubKeyRecord() {
        super(PubKey.PUB_KEY);
    }

    /**
     * Create a detached, initialised PubKeyRecord
     */
    public PubKeyRecord(Integer id, String pubKey, Integer usrId) {
        super(PubKey.PUB_KEY);

        set(0, id);
        set(1, pubKey);
        set(2, usrId);
    }
}
