/*
 * This file is generated by jOOQ.
 */
package com.example.roles.model.tables.records;


import com.example.roles.model.tables.Roles;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = -1490329706;

    /**
     * Setter for <code>public.roles.role</code>.
     */
    public void setRole(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.roles.role</code>.
     */
    public String getRole() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.roles.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.roles.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Roles.ROLES.ROLE;
    }

    @Override
    public Field<Integer> field2() {
        return Roles.ROLES.ROLE_ID;
    }

    @Override
    public String component1() {
        return getRole();
    }

    @Override
    public Integer component2() {
        return getRoleId();
    }

    @Override
    public String value1() {
        return getRole();
    }

    @Override
    public Integer value2() {
        return getRoleId();
    }

    @Override
    public RolesRecord value1(String value) {
        setRole(value);
        return this;
    }

    @Override
    public RolesRecord value2(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolesRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(String role, Integer roleId) {
        super(Roles.ROLES);

        set(0, role);
        set(1, roleId);
    }
}
