management:
  endpoints:
    web:
      exposure:
        include: info,health,refresh,env,routes
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5555
zuul:
  ignored-services: '*'
  prefix: /api
  sensitiveHeaders: Cookie,Set-Cookie

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 10000
