/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model.tables.records;


import com.movie.movieApplication.Model.tables.Crew;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrewRecord extends UpdatableRecordImpl<CrewRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -580361289;

    /**
     * Setter for <code>public.crew.crew_id</code>.
     */
    public void setCrewId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.crew.crew_id</code>.
     */
    public Integer getCrewId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.crew.lead_role</code>.
     */
    public void setLeadRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.crew.lead_role</code>.
     */
    public String getLeadRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.crew.others</code>.
     */
    public void setOthers(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.crew.others</code>.
     */
    public String getOthers() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Crew.CREW.CREW_ID;
    }

    @Override
    public Field<String> field2() {
        return Crew.CREW.LEAD_ROLE;
    }

    @Override
    public Field<String> field3() {
        return Crew.CREW.OTHERS;
    }

    @Override
    public Integer component1() {
        return getCrewId();
    }

    @Override
    public String component2() {
        return getLeadRole();
    }

    @Override
    public String component3() {
        return getOthers();
    }

    @Override
    public Integer value1() {
        return getCrewId();
    }

    @Override
    public String value2() {
        return getLeadRole();
    }

    @Override
    public String value3() {
        return getOthers();
    }

    @Override
    public CrewRecord value1(Integer value) {
        setCrewId(value);
        return this;
    }

    @Override
    public CrewRecord value2(String value) {
        setLeadRole(value);
        return this;
    }

    @Override
    public CrewRecord value3(String value) {
        setOthers(value);
        return this;
    }

    @Override
    public CrewRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrewRecord
     */
    public CrewRecord() {
        super(Crew.CREW);
    }

    /**
     * Create a detached, initialised CrewRecord
     */
    public CrewRecord(Integer crewId, String leadRole, String others) {
        super(Crew.CREW);

        set(0, crewId);
        set(1, leadRole);
        set(2, others);
    }
}
