/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model.tables.records;


import com.movie.movieApplication.Model.tables.Language;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageRecord extends UpdatableRecordImpl<LanguageRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 68467361;

    /**
     * Setter for <code>public.language.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.language.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.language.language</code>.
     */
    public void setLanguage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.language.language</code>.
     */
    public String getLanguage() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Language.LANGUAGE.LANG_ID;
    }

    @Override
    public Field<String> field2() {
        return Language.LANGUAGE.LANGUAGE_;
    }

    @Override
    public Integer component1() {
        return getLangId();
    }

    @Override
    public String component2() {
        return getLanguage();
    }

    @Override
    public Integer value1() {
        return getLangId();
    }

    @Override
    public String value2() {
        return getLanguage();
    }

    @Override
    public LanguageRecord value1(Integer value) {
        setLangId(value);
        return this;
    }

    @Override
    public LanguageRecord value2(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public LanguageRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageRecord
     */
    public LanguageRecord() {
        super(Language.LANGUAGE);
    }

    /**
     * Create a detached, initialised LanguageRecord
     */
    public LanguageRecord(Integer langId, String language) {
        super(Language.LANGUAGE);

        set(0, langId);
        set(1, language);
    }
}
