/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model.tables.records;


import com.movie.movieApplication.Model.tables.MovieRef;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovieRefRecord extends TableRecordImpl<MovieRefRecord> implements Record5<Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 904876664;

    /**
     * Setter for <code>public.movie_ref.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie_ref.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.movie_ref.cr_id</code>.
     */
    public void setCrId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie_ref.cr_id</code>.
     */
    public Integer getCrId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.movie_ref.fi_id</code>.
     */
    public void setFiId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.movie_ref.fi_id</code>.
     */
    public Integer getFiId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.movie_ref.la_id</code>.
     */
    public void setLaId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.movie_ref.la_id</code>.
     */
    public Integer getLaId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.movie_ref.ra_id</code>.
     */
    public void setRaId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.movie_ref.ra_id</code>.
     */
    public Integer getRaId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MovieRef.MOVIE_REF.ID;
    }

    @Override
    public Field<Integer> field2() {
        return MovieRef.MOVIE_REF.CR_ID;
    }

    @Override
    public Field<Integer> field3() {
        return MovieRef.MOVIE_REF.FI_ID;
    }

    @Override
    public Field<Integer> field4() {
        return MovieRef.MOVIE_REF.LA_ID;
    }

    @Override
    public Field<Integer> field5() {
        return MovieRef.MOVIE_REF.RA_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getCrId();
    }

    @Override
    public Integer component3() {
        return getFiId();
    }

    @Override
    public Integer component4() {
        return getLaId();
    }

    @Override
    public Integer component5() {
        return getRaId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getCrId();
    }

    @Override
    public Integer value3() {
        return getFiId();
    }

    @Override
    public Integer value4() {
        return getLaId();
    }

    @Override
    public Integer value5() {
        return getRaId();
    }

    @Override
    public MovieRefRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MovieRefRecord value2(Integer value) {
        setCrId(value);
        return this;
    }

    @Override
    public MovieRefRecord value3(Integer value) {
        setFiId(value);
        return this;
    }

    @Override
    public MovieRefRecord value4(Integer value) {
        setLaId(value);
        return this;
    }

    @Override
    public MovieRefRecord value5(Integer value) {
        setRaId(value);
        return this;
    }

    @Override
    public MovieRefRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieRefRecord
     */
    public MovieRefRecord() {
        super(MovieRef.MOVIE_REF);
    }

    /**
     * Create a detached, initialised MovieRefRecord
     */
    public MovieRefRecord(Integer id, Integer crId, Integer fiId, Integer laId, Integer raId) {
        super(MovieRef.MOVIE_REF);

        set(0, id);
        set(1, crId);
        set(2, fiId);
        set(3, laId);
        set(4, raId);
    }
}
