/*
 * This file is generated by jOOQ.
 */
package com.example.roles.model.tables.daos;


import com.example.roles.model.tables.Users;
import com.example.roles.model.tables.records.UsersRecord;

import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, com.example.roles.model.tables.pojos.Users, Integer> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, com.example.roles.model.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    public UsersDao(Configuration configuration) {
        super(Users.USERS, com.example.roles.model.tables.pojos.Users.class, configuration);
    }

    @Override
    public Integer getId(com.example.roles.model.tables.pojos.Users object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchRangeOfUserId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Users.USERS.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchByUserId(Integer... values) {
        return fetch(Users.USERS.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.example.roles.model.tables.pojos.Users fetchOneByUserId(Integer value) {
        return fetchOne(Users.USERS.USER_ID, value);
    }

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchRangeOfFirstName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.FIRST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchByFirstName(String... values) {
        return fetch(Users.USERS.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchRangeOfLastName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.LAST_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchByLastName(String... values) {
        return fetch(Users.USERS.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>mail BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchRangeOfMail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.MAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mail IN (values)</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchByMail(String... values) {
        return fetch(Users.USERS.MAIL, values);
    }

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchRangeOfPassword(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.PASSWORD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.example.roles.model.tables.pojos.Users> fetchByPassword(String... values) {
        return fetch(Users.USERS.PASSWORD, values);
    }
}
