/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model;


import com.rsa.rsaApplication.model.tables.PriKey;
import com.rsa.rsaApplication.model.tables.PubKey;
import com.rsa.rsaApplication.model.tables.Users;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRI_KEY_PKEY = Indexes0.PRI_KEY_PKEY;
    public static final Index PUB_KEY_PKEY = Indexes0.PUB_KEY_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRI_KEY_PKEY = Internal.createIndex("pri_key_pkey", PriKey.PRI_KEY, new OrderField[] { PriKey.PRI_KEY.ID }, true);
        public static Index PUB_KEY_PKEY = Internal.createIndex("pub_key_pkey", PubKey.PUB_KEY, new OrderField[] { PubKey.PUB_KEY.ID }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.USER_ID }, true);
    }
}
