/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.pri_key_id_seq</code>
     */
    public static final Sequence<Integer> PRI_KEY_ID_SEQ = new SequenceImpl<Integer>("pri_key_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.pub_key_id_seq</code>
     */
    public static final Sequence<Integer> PUB_KEY_ID_SEQ = new SequenceImpl<Integer>("pub_key_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.users_user_id_seq</code>
     */
    public static final Sequence<Integer> USERS_USER_ID_SEQ = new SequenceImpl<Integer>("users_user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
