/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model;


import com.rsa.rsaApplication.model.tables.PriKey;
import com.rsa.rsaApplication.model.tables.PubKey;
import com.rsa.rsaApplication.model.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.pri_key</code>.
     */
    public static final PriKey PRI_KEY = PriKey.PRI_KEY;

    /**
     * The table <code>public.pub_key</code>.
     */
    public static final PubKey PUB_KEY = PubKey.PUB_KEY;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
