/*
 * This file is generated by jOOQ.
 */
package com.jooq.jOOQ.model.tables.pojos;


import com.fasterxml.jackson.annotation.JsonTypeId;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = -984494318;

    private Integer id;
    private String  name;
    private String  dob;
    private String  department;
    private String  college;
    private String  place;

    public Student() {}

    public Student(Student value) {
        this.id = value.id;
        this.name = value.name;
        this.dob = value.dob;
        this.department = value.department;
        this.college = value.college;
        this.place = value.place;
    }

    public Student(
        Integer id,
        String  name,
        String  dob,
        String  department,
        String  college,
        String  place
    ) {
        this.id = id;
        this.name = name;
        this.dob = dob;
        this.department = department;
        this.college = college;
        this.place = place;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getCollege() {
        return this.college;
    }

    public void setCollege(String college) {
        this.college = college;
    }

    public String getPlace() {
        return this.place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(dob);
        sb.append(", ").append(department);
        sb.append(", ").append(college);
        sb.append(", ").append(place);

        sb.append(")");
        return sb.toString();
    }
}
