/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Films implements Serializable {

    private static final long serialVersionUID = -1584121513;

    private Integer filmId;
    private String  name;
    private String  description;

    public Films() {}

    public Films(Films value) {
        this.filmId = value.filmId;
        this.name = value.name;
        this.description = value.description;
    }

    public Films(
        Integer filmId,
        String  name,
        String  description
    ) {
        this.filmId = filmId;
        this.name = name;
        this.description = description;
    }

    public Integer getFilmId() {
        return this.filmId;
    }

    public void setFilmId(Integer filmId) {
        this.filmId = filmId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Films (");

        sb.append(filmId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
