/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language implements Serializable {

    private static final long serialVersionUID = 1599790268;

    private Integer langId;
    private String  language;

    public Language() {}

    public Language(Language value) {
        this.langId = value.langId;
        this.language = value.language;
    }

    public Language(
        Integer langId,
        String  language
    ) {
        this.langId = langId;
        this.language = language;
    }

    public Integer getLangId() {
        return this.langId;
    }

    public void setLangId(Integer langId) {
        this.langId = langId;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Language (");

        sb.append(langId);
        sb.append(", ").append(language);

        sb.append(")");
        return sb.toString();
    }
}
