/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ratings implements Serializable {

    private static final long serialVersionUID = 14046486;

    private Integer ratingId;
    private Integer rating;

    public Ratings() {}

    public Ratings(Ratings value) {
        this.ratingId = value.ratingId;
        this.rating = value.rating;
    }

    public Ratings(
        Integer ratingId,
        Integer rating
    ) {
        this.ratingId = ratingId;
        this.rating = rating;
    }

    public Integer getRatingId() {
        return this.ratingId;
    }

    public void setRatingId(Integer ratingId) {
        this.ratingId = ratingId;
    }

    public Integer getRating() {
        return this.rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Ratings (");

        sb.append(ratingId);
        sb.append(", ").append(rating);

        sb.append(")");
        return sb.toString();
    }
}
