/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PriKey implements Serializable {

    private static final long serialVersionUID = -1984751845;

    private Integer id;
    private String  priKey;
    private Integer usrId;

    public PriKey() {}

    public PriKey(PriKey value) {
        this.id = value.id;
        this.priKey = value.priKey;
        this.usrId = value.usrId;
    }

    public PriKey(
        Integer id,
        String  priKey,
        Integer usrId
    ) {
        this.id = id;
        this.priKey = priKey;
        this.usrId = usrId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPriKey() {
        return this.priKey;
    }

    public void setPriKey(String priKey) {
        this.priKey = priKey;
    }

    public Integer getUsrId() {
        return this.usrId;
    }

    public void setUsrId(Integer usrId) {
        this.usrId = usrId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PriKey (");

        sb.append(id);
        sb.append(", ").append(priKey);
        sb.append(", ").append(usrId);

        sb.append(")");
        return sb.toString();
    }
}
