/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1909356861;

    private Integer userId;
    private String  name;
    private String  phone;
    private String  mail;

    public Users() {}

    public Users(Users value) {
        this.userId = value.userId;
        this.name = value.name;
        this.phone = value.phone;
        this.mail = value.mail;
    }

    public Users(
        Integer userId,
        String  name,
        String  phone,
        String  mail
    ) {
        this.userId = userId;
        this.name = name;
        this.phone = phone;
        this.mail = mail;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(mail);

        sb.append(")");
        return sb.toString();
    }
}
