/*
 * This file is generated by jOOQ.
 */
package com.rsa.rsaApplication.model.tables;


import com.rsa.rsaApplication.model.Indexes;
import com.rsa.rsaApplication.model.Keys;
import com.rsa.rsaApplication.model.Public;
import com.rsa.rsaApplication.model.tables.records.PubKeyRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PubKey extends TableImpl<PubKeyRecord> {

    private static final long serialVersionUID = -1453262397;

    /**
     * The reference instance of <code>public.pub_key</code>
     */
    public static final PubKey PUB_KEY = new PubKey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PubKeyRecord> getRecordType() {
        return PubKeyRecord.class;
    }

    /**
     * The column <code>public.pub_key.id</code>.
     */
    public final TableField<PubKeyRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('pub_key_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.pub_key.pub_key</code>.
     */
    public final TableField<PubKeyRecord, String> PUB_KEY_ = createField(DSL.name("pub_key"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pub_key.usr_id</code>.
     */
    public final TableField<PubKeyRecord, Integer> USR_ID = createField(DSL.name("usr_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.pub_key</code> table reference
     */
    public PubKey() {
        this(DSL.name("pub_key"), null);
    }

    /**
     * Create an aliased <code>public.pub_key</code> table reference
     */
    public PubKey(String alias) {
        this(DSL.name(alias), PUB_KEY);
    }

    /**
     * Create an aliased <code>public.pub_key</code> table reference
     */
    public PubKey(Name alias) {
        this(alias, PUB_KEY);
    }

    private PubKey(Name alias, Table<PubKeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private PubKey(Name alias, Table<PubKeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PubKey(Table<O> child, ForeignKey<O, PubKeyRecord> key) {
        super(child, key, PUB_KEY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PUB_KEY_PKEY);
    }

    @Override
    public Identity<PubKeyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PUB_KEY;
    }

    @Override
    public UniqueKey<PubKeyRecord> getPrimaryKey() {
        return Keys.PUB_KEY_PKEY;
    }

    @Override
    public List<UniqueKey<PubKeyRecord>> getKeys() {
        return Arrays.<UniqueKey<PubKeyRecord>>asList(Keys.PUB_KEY_PKEY);
    }

    @Override
    public List<ForeignKey<PubKeyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PubKeyRecord, ?>>asList(Keys.PUB_KEY__PUB_KEY_USR_ID_FKEY);
    }

    public Users users() {
        return new Users(this, Keys.PUB_KEY__PUB_KEY_USR_ID_FKEY);
    }

    @Override
    public PubKey as(String alias) {
        return new PubKey(DSL.name(alias), this);
    }

    @Override
    public PubKey as(Name alias) {
        return new PubKey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PubKey rename(String name) {
        return new PubKey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PubKey rename(Name name) {
        return new PubKey(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
