/*
 * This file is generated by jOOQ.
 */
package com.jooq.jOOQ.model.tables.records;


import com.jooq.jOOQ.model.tables.Student;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1853903461;

    /**
     * Setter for <code>public.student.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.student.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.student.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.student.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.student.dob</code>.
     */
    public void setDob(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.student.dob</code>.
     */
    public String getDob() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.student.department</code>.
     */
    public void setDepartment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.student.department</code>.
     */
    public String getDepartment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.student.college</code>.
     */
    public void setCollege(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.student.college</code>.
     */
    public String getCollege() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.student.place</code>.
     */
    public void setPlace(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.student.place</code>.
     */
    public String getPlace() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Student.STUDENT.ID;
    }

    @Override
    public Field<String> field2() {
        return Student.STUDENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return Student.STUDENT.DOB;
    }

    @Override
    public Field<String> field4() {
        return Student.STUDENT.DEPARTMENT;
    }

    @Override
    public Field<String> field5() {
        return Student.STUDENT.COLLEGE;
    }

    @Override
    public Field<String> field6() {
        return Student.STUDENT.PLACE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDob();
    }

    @Override
    public String component4() {
        return getDepartment();
    }

    @Override
    public String component5() {
        return getCollege();
    }

    @Override
    public String component6() {
        return getPlace();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDob();
    }

    @Override
    public String value4() {
        return getDepartment();
    }

    @Override
    public String value5() {
        return getCollege();
    }

    @Override
    public String value6() {
        return getPlace();
    }

    @Override
    public StudentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StudentRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StudentRecord value3(String value) {
        setDob(value);
        return this;
    }

    @Override
    public StudentRecord value4(String value) {
        setDepartment(value);
        return this;
    }

    @Override
    public StudentRecord value5(String value) {
        setCollege(value);
        return this;
    }

    @Override
    public StudentRecord value6(String value) {
        setPlace(value);
        return this;
    }

    @Override
    public StudentRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer id, String name, String dob, String department, String college, String place) {
        super(Student.STUDENT);

        set(0, id);
        set(1, name);
        set(2, dob);
        set(3, department);
        set(4, college);
        set(5, place);
    }
}
