/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model;


import com.movie.movieApplication.Model.tables.Crew;
import com.movie.movieApplication.Model.tables.Films;
import com.movie.movieApplication.Model.tables.Language;
import com.movie.movieApplication.Model.tables.Ratings;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CREW_PKEY = Indexes0.CREW_PKEY;
    public static final Index FILMS_PKEY = Indexes0.FILMS_PKEY;
    public static final Index LANGUAGE_PKEY = Indexes0.LANGUAGE_PKEY;
    public static final Index RATINGS_PKEY = Indexes0.RATINGS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CREW_PKEY = Internal.createIndex("crew_pkey", Crew.CREW, new OrderField[] { Crew.CREW.CREW_ID }, true);
        public static Index FILMS_PKEY = Internal.createIndex("films_pkey", Films.FILMS, new OrderField[] { Films.FILMS.FILM_ID }, true);
        public static Index LANGUAGE_PKEY = Internal.createIndex("language_pkey", Language.LANGUAGE, new OrderField[] { Language.LANGUAGE.LANG_ID }, true);
        public static Index RATINGS_PKEY = Internal.createIndex("ratings_pkey", Ratings.RATINGS, new OrderField[] { Ratings.RATINGS.RATING_ID }, true);
    }
}
