/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model;


import com.movie.movieApplication.Model.tables.Crew;
import com.movie.movieApplication.Model.tables.Films;
import com.movie.movieApplication.Model.tables.Language;
import com.movie.movieApplication.Model.tables.MovieRef;
import com.movie.movieApplication.Model.tables.Ratings;
import com.movie.movieApplication.Model.tables.records.CrewRecord;
import com.movie.movieApplication.Model.tables.records.FilmsRecord;
import com.movie.movieApplication.Model.tables.records.LanguageRecord;
import com.movie.movieApplication.Model.tables.records.MovieRefRecord;
import com.movie.movieApplication.Model.tables.records.RatingsRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CrewRecord, Integer> IDENTITY_CREW = Identities0.IDENTITY_CREW;
    public static final Identity<FilmsRecord, Integer> IDENTITY_FILMS = Identities0.IDENTITY_FILMS;
    public static final Identity<LanguageRecord, Integer> IDENTITY_LANGUAGE = Identities0.IDENTITY_LANGUAGE;
    public static final Identity<MovieRefRecord, Integer> IDENTITY_MOVIE_REF = Identities0.IDENTITY_MOVIE_REF;
    public static final Identity<RatingsRecord, Integer> IDENTITY_RATINGS = Identities0.IDENTITY_RATINGS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CrewRecord> CREW_PKEY = UniqueKeys0.CREW_PKEY;
    public static final UniqueKey<FilmsRecord> FILMS_PKEY = UniqueKeys0.FILMS_PKEY;
    public static final UniqueKey<LanguageRecord> LANGUAGE_PKEY = UniqueKeys0.LANGUAGE_PKEY;
    public static final UniqueKey<RatingsRecord> RATINGS_PKEY = UniqueKeys0.RATINGS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MovieRefRecord, CrewRecord> MOVIE_REF__CR_ID_FK = ForeignKeys0.MOVIE_REF__CR_ID_FK;
    public static final ForeignKey<MovieRefRecord, FilmsRecord> MOVIE_REF__FI_ID_FK = ForeignKeys0.MOVIE_REF__FI_ID_FK;
    public static final ForeignKey<MovieRefRecord, LanguageRecord> MOVIE_REF__LA_ID_FK = ForeignKeys0.MOVIE_REF__LA_ID_FK;
    public static final ForeignKey<MovieRefRecord, RatingsRecord> MOVIE_REF__RA_ID_FK = ForeignKeys0.MOVIE_REF__RA_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CrewRecord, Integer> IDENTITY_CREW = Internal.createIdentity(Crew.CREW, Crew.CREW.CREW_ID);
        public static Identity<FilmsRecord, Integer> IDENTITY_FILMS = Internal.createIdentity(Films.FILMS, Films.FILMS.FILM_ID);
        public static Identity<LanguageRecord, Integer> IDENTITY_LANGUAGE = Internal.createIdentity(Language.LANGUAGE, Language.LANGUAGE.LANG_ID);
        public static Identity<MovieRefRecord, Integer> IDENTITY_MOVIE_REF = Internal.createIdentity(MovieRef.MOVIE_REF, MovieRef.MOVIE_REF.ID);
        public static Identity<RatingsRecord, Integer> IDENTITY_RATINGS = Internal.createIdentity(Ratings.RATINGS, Ratings.RATINGS.RATING_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CrewRecord> CREW_PKEY = Internal.createUniqueKey(Crew.CREW, "crew_pkey", Crew.CREW.CREW_ID);
        public static final UniqueKey<FilmsRecord> FILMS_PKEY = Internal.createUniqueKey(Films.FILMS, "films_pkey", Films.FILMS.FILM_ID);
        public static final UniqueKey<LanguageRecord> LANGUAGE_PKEY = Internal.createUniqueKey(Language.LANGUAGE, "language_pkey", Language.LANGUAGE.LANG_ID);
        public static final UniqueKey<RatingsRecord> RATINGS_PKEY = Internal.createUniqueKey(Ratings.RATINGS, "ratings_pkey", Ratings.RATINGS.RATING_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<MovieRefRecord, CrewRecord> MOVIE_REF__CR_ID_FK = Internal.createForeignKey(com.movie.movieApplication.Model.Keys.CREW_PKEY, MovieRef.MOVIE_REF, "movie_ref__cr_id_fk", MovieRef.MOVIE_REF.CR_ID);
        public static final ForeignKey<MovieRefRecord, FilmsRecord> MOVIE_REF__FI_ID_FK = Internal.createForeignKey(com.movie.movieApplication.Model.Keys.FILMS_PKEY, MovieRef.MOVIE_REF, "movie_ref__fi_id_fk", MovieRef.MOVIE_REF.FI_ID);
        public static final ForeignKey<MovieRefRecord, LanguageRecord> MOVIE_REF__LA_ID_FK = Internal.createForeignKey(com.movie.movieApplication.Model.Keys.LANGUAGE_PKEY, MovieRef.MOVIE_REF, "movie_ref__la_id_fk", MovieRef.MOVIE_REF.LA_ID);
        public static final ForeignKey<MovieRefRecord, RatingsRecord> MOVIE_REF__RA_ID_FK = Internal.createForeignKey(com.movie.movieApplication.Model.Keys.RATINGS_PKEY, MovieRef.MOVIE_REF, "movie_ref__ra_id_fk", MovieRef.MOVIE_REF.RA_ID);
    }
}
