/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.crew_crew_id_seq</code>
     */
    public static final Sequence<Integer> CREW_CREW_ID_SEQ = new SequenceImpl<Integer>("crew_crew_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.films_film_id_seq</code>
     */
    public static final Sequence<Integer> FILMS_FILM_ID_SEQ = new SequenceImpl<Integer>("films_film_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.language_lang_id_seq</code>
     */
    public static final Sequence<Integer> LANGUAGE_LANG_ID_SEQ = new SequenceImpl<Integer>("language_lang_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.movie_ref_id_seq</code>
     */
    public static final Sequence<Integer> MOVIE_REF_ID_SEQ = new SequenceImpl<Integer>("movie_ref_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.ratings_rating_id_seq</code>
     */
    public static final Sequence<Integer> RATINGS_RATING_ID_SEQ = new SequenceImpl<Integer>("ratings_rating_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
