/*
 * This file is generated by jOOQ.
 */
package com.movie.movieApplication.Model;


import com.movie.movieApplication.Model.tables.Crew;
import com.movie.movieApplication.Model.tables.Films;
import com.movie.movieApplication.Model.tables.Language;
import com.movie.movieApplication.Model.tables.MovieRef;
import com.movie.movieApplication.Model.tables.Ratings;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.crew</code>.
     */
    public static final Crew CREW = Crew.CREW;

    /**
     * The table <code>public.films</code>.
     */
    public static final Films FILMS = Films.FILMS;

    /**
     * The table <code>public.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.movie_ref</code>.
     */
    public static final MovieRef MOVIE_REF = MovieRef.MOVIE_REF;

    /**
     * The table <code>public.ratings</code>.
     */
    public static final Ratings RATINGS = Ratings.RATINGS;
}
