/*
 * This file is generated by jOOQ.
 */
package com.example.roles.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefDetails implements Serializable {

    private static final long serialVersionUID = -102252544;

    private Integer refId;
    private Integer rolId;
    private Integer useId;

    public RefDetails() {}

    public RefDetails(RefDetails value) {
        this.refId = value.refId;
        this.rolId = value.rolId;
        this.useId = value.useId;
    }

    public RefDetails(
        Integer refId,
        Integer rolId,
        Integer useId
    ) {
        this.refId = refId;
        this.rolId = rolId;
        this.useId = useId;
    }

    public Integer getRefId() {
        return this.refId;
    }

    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    public Integer getRolId() {
        return this.rolId;
    }

    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }

    public Integer getUseId() {
        return this.useId;
    }

    public void setUseId(Integer useId) {
        this.useId = useId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RefDetails (");

        sb.append(refId);
        sb.append(", ").append(rolId);
        sb.append(", ").append(useId);

        sb.append(")");
        return sb.toString();
    }
}
