/*
 * This file is generated by jOOQ.
 */
package com.example.roles.model;


import com.example.roles.model.tables.RefDetails;
import com.example.roles.model.tables.Roles;
import com.example.roles.model.tables.Users;
import com.example.roles.model.tables.records.RefDetailsRecord;
import com.example.roles.model.tables.records.RolesRecord;
import com.example.roles.model.tables.records.UsersRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RefDetailsRecord, Integer> IDENTITY_REF_DETAILS = Identities0.IDENTITY_REF_DETAILS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RefDetailsRecord> REF_DETAILS_PKEY = UniqueKeys0.REF_DETAILS_PKEY;
    public static final UniqueKey<RolesRecord> ROLES_PKEY = UniqueKeys0.ROLES_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RefDetailsRecord, RolesRecord> REF_DETAILS__REF_DETAILS_ROL_ID_FKEY = ForeignKeys0.REF_DETAILS__REF_DETAILS_ROL_ID_FKEY;
    public static final ForeignKey<RefDetailsRecord, UsersRecord> REF_DETAILS__REF_DETAILS_USE_ID_FKEY = ForeignKeys0.REF_DETAILS__REF_DETAILS_USE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RefDetailsRecord, Integer> IDENTITY_REF_DETAILS = Internal.createIdentity(RefDetails.REF_DETAILS, RefDetails.REF_DETAILS.REF_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RefDetailsRecord> REF_DETAILS_PKEY = Internal.createUniqueKey(RefDetails.REF_DETAILS, "ref_details_pkey", RefDetails.REF_DETAILS.REF_ID);
        public static final UniqueKey<RolesRecord> ROLES_PKEY = Internal.createUniqueKey(Roles.ROLES, "roles_pkey", Roles.ROLES.ROLE_ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.USER_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<RefDetailsRecord, RolesRecord> REF_DETAILS__REF_DETAILS_ROL_ID_FKEY = Internal.createForeignKey(com.example.roles.model.Keys.ROLES_PKEY, RefDetails.REF_DETAILS, "ref_details__ref_details_rol_id_fkey", RefDetails.REF_DETAILS.ROL_ID);
        public static final ForeignKey<RefDetailsRecord, UsersRecord> REF_DETAILS__REF_DETAILS_USE_ID_FKEY = Internal.createForeignKey(com.example.roles.model.Keys.USERS_PKEY, RefDetails.REF_DETAILS, "ref_details__ref_details_use_id_fkey", RefDetails.REF_DETAILS.USE_ID);
    }
}
