/*
 * This file is generated by jOOQ.
 */
package com.example.roles.model;


import com.example.roles.model.tables.RefDetails;
import com.example.roles.model.tables.Roles;
import com.example.roles.model.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1904077759;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ref_details</code>.
     */
    public final RefDetails REF_DETAILS = com.example.roles.model.tables.RefDetails.REF_DETAILS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = com.example.roles.model.tables.Roles.ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = com.example.roles.model.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.REF_DETAILS_REF_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            RefDetails.REF_DETAILS,
            Roles.ROLES,
            Users.USERS);
    }
}
