/*
 * This file is generated by jOOQ.
 */
package com.example.roles.model;


import com.example.roles.model.tables.RefDetails;
import com.example.roles.model.tables.Roles;
import com.example.roles.model.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ref_details</code>.
     */
    public static final RefDetails REF_DETAILS = RefDetails.REF_DETAILS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
